# This workflow will install Swap package dependencies, run tests and lint with a variety of Python versions.

name: workflow

on:
  push:
    branches: [
      master
    ]
  pull_request:
    branches: [
      master
    ]

jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [
          "3.9", "3.10", "3.11"
        ]
    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[tests]
    - name: Test with pytest
      run: pytest
